spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3307}/${DB_NAME:virtualpet}
    username: ${DB_USER:ignasi}
    password: ${DB_PASSWORD:ignasi123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

app:
  admin:
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:admin123}
    email: ${ADMIN_EMAIL:admin@virtualpet.com}

  pet:
    hunger:
      increasePerHour: 5
    aggressiveness:
      increasePerHour: 3

springdoc:
  swagger-ui:
    customCssUrl: /swagger-custom.cc
