spring:
  datasource:
    url: jdbc:mysql://localhost:3307/virtualpet
    username: ignasi
    password: ignasi123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


  profiles:
    active: dev

  pet:
    hunger:
      increasePerHour: 5
    aggressiveness:
        increasePerHour: 3

  springdoc:
    swagger-ui:
      customCssUrl : /swagger-custom.cc
